name: proyecto-ar-g13
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - ipykernel
  - libstdcxx-ng
  - pip:
      - gym==0.17.3
      - git+https://github.com/Kojoley/atari-py.git
      - keras-rl2==1.0.5
      - tensorflow==2.12
